### ISSUE TITLE
Affichage des annotations en bas d’écran

### ISSUE THREAD

**Issue by CLaduron** [cytomine/Cytomine-tools#2]
la fenêtre d’option de chaque annotation s’affiche en « arrière-plan » (voir screenshot). Observé sur Safari, sur un Macbook 15 pouces.
<img width="872" alt="probleme affichage annotations" src="https://cloud.githubusercontent.com/assets/17763941/15245563/99c3437a-1907-11e6-828e-afec70e9a3fb.png">

**Comment by geektortoise** [comment]
Please, for the UI, create your ticket into the Cytomine-core repository.
This repo is for utility tools used outside of the application.
I made a quick fix for this problem (https://github.com/cytomine/Cytomine-core/commit/f993408dbd6ab9c87cf006a5b5c5517e7450383f).
